version: 0.2

phases:
  pre_build:
    commands:
      - echo Working with $REPOSITORY_URI
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin $REPOSITORY_URI
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - BUILD_TAG=${COMMIT_HASH:=latest}

  build:
    commands:
      - echo Building image with tag $BUILD_TAG
      - echo Build started on `date`
      - echo Building the Java Docker image...
      - cd java_timetracking
      - docker build -t $REPOSITORY_URI/javaapp:latest .
      - docker tag $REPOSITORY_URI/javaapp:latest $REPOSITORY_URI/javaapp
      - cd ..
      - echo Building the React Docker image...
      - cd react_timetracking
      - docker build -t $REPOSITORY_URI/reactapp:latest .
      - docker tag $REPOSITORY_URI/reactapp:latest $REPOSITORY_URI/reactapp
      - cd ..

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI/javaapp:latest
      - docker push $REPOSITORY_URI/javaapp:$BUILD_TAG
      - docker push $REPOSITORY_URI/reactapp:latest
      - docker push $REPOSITORY_URI/reactapp:$BUILD_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"java-container","imageUri":"%s"},{"name":"react-container","imageUri":"%s"}]' $REPOSITORY_URI/javaapp:$BUILD_TAG $REPOSITORY_URI/reactapp:$BUILD_TAG > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
